import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,cp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
const data=await mkdtemp(join(tmpdir(),'org-webpage-test-'));
for(const name of ['topics.json','relationships.json','relationship-analysis.json','relationship-matrix.json','source-map.json'])await cp('data/'+name,join(data,name));
let server,browser;
const errors=[];
async function startServer(){server=spawn(process.execPath,['server.mjs'],{cwd:resolve('.'),env:{...process.env,PORT:'4318',ORG_DATA_DIR:data},stdio:['ignore','pipe','pipe']});await new Promise((yes,no)=>{server.stdout.on('data',v=>{if(v.toString().includes('http://'))yes();});server.stderr.on('data',v=>no(new Error(v.toString())));server.on('error',no);});}
try {
  await startServer();browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1500,height:1000}});page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.testTools={};Object.defineProperty(document,'modelContext',{value:{registerTool:tool=>window.testTools[tool.name]=tool}});});
  await page.goto('http://localhost:4318');await page.waitForFunction(()=>window.orgGraph);
  assert.equal((await page.evaluate(()=>orgGraph.snapshot())).edgeCount,333);
  await page.locator('#search').fill('begrenset');await page.locator('.result').first().click();
  await page.waitForTimeout(400);
  let s=await page.evaluate(()=>orgGraph.snapshot());assert.equal(s.selected,'begrenset-rasjonalitet');
  let n=s.nodes.find(n=>n.id===s.selected);assert.ok(Math.abs(n.screen[0]-s.width/2)<4);assert.ok(Math.abs(n.screen[1]-s.height/2)<4);
  const rect=await page.locator('canvas').boundingBox();await page.mouse.click(n.screen[0]+rect.x,n.screen[1]+rect.y,{button:'right'});
  await page.locator('#edit-topic').waitFor();assert.equal(await page.locator('#sidebar').isVisible(),true);
  await page.locator('#edit-topic').click();await page.locator('#edit-notes').fill('Persistenssjekk: æøå <script>test</script>');await page.locator('#edit-explanation').fill('Testforklaring som lagres og overlever omstart.');await page.locator('#edit-topic').click();await page.getByText('Endringene er lagret.',{exact:true}).waitFor();
  const edits=JSON.parse(await readFile(join(data,'edits.json'),'utf8'));assert.equal(edits.topics['begrenset-rasjonalitet'].version,1);
  const stale=await page.evaluate(async()=>{const t=await fetch('/api/topics').then(r=>r.json());const topic=t.topics.find(t=>t.id==='begrenset-rasjonalitet');return (await fetch('/api/topics/begrenset-rasjonalitet',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:0,notes:'bad',fields:{title:topic.title}})})).status;});assert.equal(stale,409);
  await page.reload();await page.waitForFunction(()=>window.orgGraph);assert.equal(await page.evaluate(()=>orgGraph.topic('begrenset-rasjonalitet').content.explanation),'Testforklaring som lagres og overlever omstart.');
  const exited=new Promise(r=>server.once('exit',r));server.kill();await exited;await startServer();await page.reload();await page.waitForFunction(()=>window.orgGraph);assert.equal(await page.evaluate(()=>orgGraph.topic('begrenset-rasjonalitet')._edit.notes),'Persistenssjekk: æøå <script>test</script>');
  await page.locator('#focus').selectOption('organisasjon');await page.locator('#threshold-value').fill('1.00');await page.locator('#threshold-value').press('Tab');await page.waitForTimeout(170);s=await page.evaluate(()=>orgGraph.snapshot());assert.equal(s.nodes.length,1);assert.equal(s.edgeCount,0);
  await page.locator('#clear-focus').click();s=await page.evaluate(()=>orgGraph.snapshot());assert.equal(s.nodes.length,132);
  await page.locator('#threshold-value').fill('0.01');await page.locator('#threshold-value').press('Tab');await page.waitForTimeout(220);s=await page.evaluate(()=>orgGraph.snapshot());assert.equal(s.edgeCount,8646);
  await page.locator('#threshold-value').fill('0.88');await page.locator('#threshold-value').press('Tab');await page.waitForTimeout(150);
  await page.locator('#static').click();const before=await page.evaluate(()=>orgGraph.snapshot().nodes);await page.waitForTimeout(250);const after=await page.evaluate(()=>orgGraph.snapshot().nodes);assert.deepEqual(before,after);
  await page.locator('#search').fill('organisasjon');await page.locator('.result[data-id="organisasjon"]').click();
  s=await page.evaluate(()=>orgGraph.snapshot());n=s.nodes.find(n=>n.id==='organisasjon');const box=await page.locator('canvas').boundingBox();
  await page.mouse.move(n.screen[0]+box.x,n.screen[1]+box.y);await page.mouse.down();await page.mouse.move(n.screen[0]+box.x+85,n.screen[1]+box.y+30,{steps:8});await page.mouse.up();
  const moved=await page.evaluate(()=>orgGraph.snapshot().nodes.find(n=>n.id==='organisasjon'));assert.ok(Math.abs(moved.x-n.x)*s.zoom>60,JSON.stringify({before:n.x,after:moved.x,zoom:s.zoom}));
  await page.waitForTimeout(250);assert.equal((await page.evaluate(()=>orgGraph.snapshot().nodes.find(n=>n.id==='organisasjon'))).x,moved.x);
  await page.locator('#dynamic').click();await page.waitForTimeout(350);const elastic=await page.evaluate(()=>orgGraph.snapshot().nodes.find(n=>n.id==='organisasjon'));assert.notEqual(elastic.x,moved.x);
  const zoom=(await page.evaluate(()=>orgGraph.snapshot())).zoom;await page.locator('#zoom-in').click();assert.ok((await page.evaluate(()=>orgGraph.snapshot())).zoom>zoom);
  await page.locator('#fit').click();
  const tools=await page.evaluate(()=>Object.keys(window.testTools));assert.deepEqual(tools.sort(),['configure_graph_view','read_graph_state']);
  const toolResult=await page.evaluate(()=>testTools.configure_graph_view.execute({threshold:1,focus_id:'organisasjon'}));assert.equal(toolResult.node_count,1);
  assert.equal(await page.evaluate(async()=>{try{await testTools.configure_graph_view.execute({threshold:0});return false;}catch{return true;}}),true);
  await page.evaluate(()=>testTools.configure_graph_view.execute({threshold:.88,focus_id:null}));
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#search').fill('organisasjon');await page.locator('.result[data-id="organisasjon"]').click();await page.locator('canvas').press('Enter');assert.equal(await page.locator('#sidebar').isVisible(),true);
  assert.ok((await page.locator('#edit-topic').boundingBox()).x>=0);
  assert.deepEqual(errors,[]);
  await page.locator('#close-sidebar').click();await page.locator('#updates-button').click();await page.locator('#content-check').waitFor();assert.ok(await page.locator('#backup-export').isVisible());await page.locator('#sync-close').click();
  console.log('PASS: browser load, search centering, right-click, saved edits, restart persistence, stale-write protection, focus reachability, threshold extremes, static drag, elasticity, zoom, mobile, keyboard, WebMCP valid/invalid inputs; no browser errors.');
} finally {if(browser)await browser.close();if(server&&server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}assert.ok(resolve(data).startsWith(resolve(tmpdir())+sep+'org-webpage-test-'));await rm(data,{recursive:true,force:true});}
