// Original paraphrases and fictional cases. Source PDFs are deliberately not distributed.
export const ref=(n,start,end=start)=>({source_id:`course-2026-${String(n).padStart(2,'0')}`,locator:`PDF-side ${start}${end===start?'':`–${end}`}${n===14?` (bokside ${start+313}–${end+313})`:n===15?` (bokside ${start+125}–${end+125})`:''}`,paragraph_start:start,paragraph_end:end,pages:Array.from({length:end-start+1},(_,i)=>start+i+(n===14?313:n===15?125:0))});
export const additions=[];
function add(id,title,category,definition,explanation,points,source,example,links){
 additions.push({id,title,category,definition,explanation,points:points.split('|'),source,example,links});
}
add('tjenende-ledelse','Greenleaf: tjenende ledelse','ledelse',
'Ledelse som prioriterer medarbeidernes utvikling og et ansvarlig bidrag til fellesskapet.',
'Lederens innflytelse brukes til å gjøre andre bedre i stand til å handle selvstendig. Forelesningen knytter tradisjonen til Robert Greenleaf og presenterer seks atferdsdimensjoner. Tjenende ledelse omfatter også tydelig retning og ansvar; den innebærer ikke at lederen skal oppfylle alle ønsker. Tillit og utvikling må vurderes sammen med oppgaven, maktforholdene og medarbeidernes behov.',
'Myndiggjøring og utvikling: gi handlingsrom, støtte og læringsmuligheter.|Ydmykhet: erkjenne egne begrensninger og ta imot kritikk.|Autentisitet: opptre troverdig og i samsvar med uttrykte verdier.|Mellommenneskelig aksept: møte andre med respekt og håndtere feil uten å redusere personen til feilen.|Retning: avklare mål, ansvar og grenser.|Forvalteransvar: ivareta fellesskapet og langsiktige hensyn.',[ref(4,15,17),ref(4,31,34)],
'Et kommunalt serviceteam får ansvar for en ny veiledningstjeneste. Lederen lar medarbeiderne utforme samtalene og setter av tid til opplæring: myndiggjøring og utvikling. Hun innrømmer at hennes første løsning var for komplisert, og ber nyansatte om kritikk: ydmykhet. Hun har lovet å prioritere tilgjengelighet og deltar selv i utprøvingen: autentisitet.\n\nNår en medarbeider gir feil informasjon, undersøker hun hendelsen respektfullt, samtidig som feilen rettes: mellommenneskelig aksept uten å oppheve ansvar. Hun klargjør hvem som kvalitetssikrer svar og hvilke saker som må løftes videre: retning. Hun avslår en snarvei som ville gitt fine måltall, men dårligere hjelp til sårbare brukere: forvalteransvar. Eksemplet viser hvordan støtte og krav kan kombineres. Det dokumenterer ikke at lederstilen alltid gir bedre resultater.',
[['bemyndiggjoring',.94,'Tjenende ledelse konkretiserer hvordan myndighet og utviklingsmuligheter kan deles.'],['etisk-ledelse',.92,'Begge tematiserer ansvarlig bruk av makt, men tjenende ledelse legger særlig vekt på andres vekst.'],['selvbestemmelsesteori',.89,'Støtte til autonomi, kompetanse og tilhørighet gir en forklaringsbro til motivasjon.'],['lmx',.84,'Respekt og tillit i relasjonen kan støtte utvikling, men tjenesteidealet gjelder mer enn en enkelt dyade.']]);
add('kotter-endring','Kotter: åtte endringstrinn','endring',
'Et rammeverk for å mobilisere, gjennomføre og forankre planlagt organisasjonsendring.',
'Trinnene synliggjør både politisk oppslutning, praktisk gjennomføring og kulturell forankring. De fungerer som spørsmål til en endringsprosess, ikke som en garanti eller en mekanisk oppskrift som alltid følger samme tidsrekkefølge.',
'Skape forståelse for nødvendighet.|Bygge en ledende koalisjon.|Utvikle visjon og strategi.|Kommunisere retningen i ord og handling.|Fjerne hindringer og gi mulighet til å handle.|Skape synlige kortsiktige gevinster.|Bruke fremgangen til videre forbedringer.|Forankre nye arbeidsmåter i kulturen.',[ref(2,25)],
'Et bibliotek vil gjøre utlån tilgjengelig for personer som ikke kan møte fysisk. Først viser det udekkede behov og skaper forståelse for hvorfor endring trengs. Deretter samler det en koalisjon av bibliotekarer, IT og brukerrepresentanter. De lager en visjon om tilgjengelig utlån og en strategi med levering og digital bestilling.\n\nRetningen forklares i møter og demonstreres med prøvebestillinger. Uklare fullmakter og manglende opplæring fjernes som hindringer. En liten pilot gir en kortsiktig gevinst: flere brukere får bøker uten ekstra ventetid. Teamet bruker tilbakemeldingene til å forbedre logistikken og utvide tilbudet. Til slutt inngår arbeidsmåten i opplæring, budsjetter og fortellinger om god service. Hvis piloten avdekker problemer, går de tilbake og justerer; åtte avkryssede trinn beviser ikke at tilbudet virker.',
[['lewin',.94,'Kotter utdyper mobilisering, gjennomføring og forankring som også står sentralt hos Lewin.'],['endringsgjennomfoering',.96,'Trinnene konkretiserer flere av gjennomføringsbetingelsene.'],['organisasjonskultur',.86,'Forankring krever at nye handlinger blir en del av praksis og normer.']]);
add('pliktetikk','Kant: pliktetikk','ledelse','Etiske vurderinger som legger vekt på plikter, prinsipper og respekt for mennesker.',
'En handling vurderes ikke bare etter om den gir et ønsket resultat. Kants perspektiv spør om handlingsregelen kan forsvares som allmenn regel, og om personer behandles som mål i seg selv. Plikter kan komme i konflikt og krever begrunnelse; pliktetikk er ikke det samme som ukritisk lydighet mot en leder eller lovtekst.',
'Undersøk regelen bak handlingen, ikke bare enkeltutfallet.|Vurder om regelen kan gjelde for alle i tilsvarende situasjoner.|Respekter menneskers verdighet og unngå å bruke dem bare som midler.|Synliggjør konflikter mellom plikter.',[ref(5,22),ref(5,35)],
'En leder kan pynte på et kvalitetsresultat for å sikre finansiering til en nyttig tjeneste. Hun formulerer regelen: «Det er akseptabelt å villede når det gagner min avdeling.» Hvis alle fulgte den, ville rapporteringen miste troverdighet. Brukerne og finansieringsparten ville dessuten bli brukt som midler uten mulighet til å ta informerte valg.\n\nHun rapporterer derfor avviket ærlig og foreslår tiltak. Samtidig må hun ivareta medarbeiderens fortrolighet, så hun beskriver systemfeilen uten unødvendige personopplysninger. Her oppstår en avveining mellom sannferdighet og vern av personer. Analysen begrunner valget gjennom prinsipper og respekt; at ærlighet også kan lønne seg på sikt, er et tillegg og ikke selve pliktbegrunnelsen.',
[['etisk-ledelse',.93,'Pliktetikk gir et normativt grunnlag for lederens valg.'],['march-passendehet',.76,'Begge kan vise til handlingsregler, men en passende norm er ikke automatisk moralsk forsvarlig.'],['regelmodellen',.72,'Etiske prinsipper kan brukes til å kritisere organisatoriske regler.']]);
add('konsekvensetikk','Konsekvensetikk','ledelse','Vurdering av handlingers moralske verdi ut fra konsekvensene for berørte parter.',
'Analysen sammenligner alternativer og deres forventede virkninger. Utilitaristiske varianter legger vekt på samlet nytte, men må også diskutere hvem som får gevinstene og bærer kostnadene. Usikre og langsiktige virkninger må synliggjøres. At et tiltak når organisasjonens mål, gjør det ikke alene etisk godt.',
'Kartlegg realistiske alternativer og berørte parter.|Vurder både positive og negative, kortsiktige og langsiktige følger.|Drøft usikkerhet og fordeling av byrder.|Skille organisasjonens egeninteresse fra samlet etisk vurdering.',[ref(5,17,18),ref(5,23,26)],
'Et servicesenter vurderer å stenge skranken og bare tilby digitale søknader. Digital drift sparer penger og gir raskere svar til mange. Samtidig kan noen brukere miste reell tilgang, og ansatte kan få mer krevende telefonhenvendelser. Lederen sammenligner full digitalisering, uendret drift og en kombinasjon med veiledning enkelte dager.\n\nHun vurderer kostnad, tilgjengelighet, ventetid og langsiktige følger for tillit, og undersøker usikre antakelser gjennom en pilot. Kombinasjonen kan gi størst samlet nytte selv om den er dyrere enn full stenging. Hun synliggjør likevel hvem som taper. En beregning som bare teller budsjettgevinst, ville oversett vesentlige konsekvenser; rettigheter kan dessuten sette grenser som må drøftes med andre etiske perspektiver.',
[['pliktetikk',.95,'En sentral etisk kontrast mellom konsekvenser og prinsipielle grenser.'],['march-konsekvenslogikk',.89,'Konsekvenslogikk strukturerer valg; konsekvensetikk tilfører en moralsk vurdering av hvem som berøres.'],['interessentmodellen',.88,'Interessenter synliggjør hvem som får gevinster og byrder.']]);
add('dydsetikk','Aristoteles: dydsetikk','ledelse','Etikk som retter oppmerksomheten mot karakter, dømmekraft og innøvde gode handlemåter.',
'Spørsmålet er hvilken leder eller medarbeider man bør være, og hvordan praktisk klokskap utvikles gjennom erfaring og øvelse. Dyder hjelper aktøren å håndtere konkrete situasjoner; de kan ikke reduseres til en liste med personlighetstrekk eller til at man alltid velger et matematisk midtpunkt.',
'Klokskap: forstå situasjonen og vurdere hva som er godt å gjøre.|Rettferdighet: behandle andre på en forsvarlig måte.|Mot: handle til tross for risiko når saken krever det.|Måtehold: begrense egne impulser og maktbruk.|Karakter utvikles gjennom praksis og refleksjon.',[ref(5,25),ref(5,28,29),ref(5,38,39)],
'En prosjektleder oppdager at teamets tidsfrist bare kan nås ved å skjule en feil. Klokskap innebærer å undersøke alvoret og mulige løsninger før hun reagerer. Rettferdighet innebærer å høre både utvikleren og dem som blir rammet av feilen, i stedet for å utpeke en syndebukk. Mot viser hun når hun forteller ledelsen at leveransen må utsettes.\n\nMåtehold viser hun ved å motstå fristelsen til å holde en offentlig utskjelling, selv om hun er frustrert. Etterpå gjennomgår teamet hvordan de kan varsle tidligere. Når hun gjentar slike handlinger over tid, blir ansvarlig praksis en vane og et forbilde. Eksemplet handler om utviklet dømmekraft, ikke om at en «god person» automatisk har rett i alle beslutninger.',
[['etisk-ledelse',.92,'Rollemodeller og praktisk dømmekraft forbinder dydsetikk med lederatferd.'],['sosial-laering',.84,'Dyder kan illustreres og øves gjennom observasjon og handling.'],['autentisk-ledelse',.79,'Samsvar med egne verdier er relevant, men verdiene må også kunne forsvares etisk.']]);
add('diskursetikk','Habermas: diskursetikk','ledelse','Etisk begrunnelse gjennom en åpen dialog der berørte parter kan prøve argumenter uten tvang.',
'Legitimitet søkes gjennom begrunnelser som berørte parter kan diskutere på likeverdige vilkår. Reell mulighet til å delta, sannferdighet og fravær av maktpress er sentralt. Enighet alene er ikke tilstrekkelig hvis noen er ekskludert, mangler informasjon eller ikke våger å si imot.',
'Gi berørte parter en reell stemme.|Legg frem relevant informasjon og etterprøvbare begrunnelser.|La argumentenes styrke telle mer enn rang og sanksjoner.|Vær villig til å revidere eget standpunkt.',[ref(5,37),ref(10,17)],
'Et sykehjem skal fordele ubekvemme vakter. Ledelsen inviterer ansatte fra alle skift og deres representanter, også deltidsansatte som vanligvis ikke møter på dagmøter. Før samtalen får alle samme informasjon om bemanning og behov. En møteleder sørger for at uenighet ikke påvirker senere vaktfordeling.\n\nDeltakerne forklarer hvilke hensyn de mener er rimelige, og utfordrer både lederens forslag og egne antakelser. Forslaget endres når en nattarbeider viser en oversett belastning. Begrunnelsen dokumenteres, og fraværende får kommentere før endelig behandling. Diskursetisk kvalitet ligger i vilkårene for dialogen og muligheten for begrunnet kritikk. Et raskt ja fra en taus gruppe ville ikke være nok.',
[['kommunikativ-rasjonalitet',.97,'Diskursetikk anvender idealer om fri og begrunnet dialog på moralske normer.'],['bemyndiggjoring',.86,'Reell deltakelse krever at svake stemmer får innflytelse.'],['forhandlingsmodeller',.82,'Sammenlign argumentbasert normbegrunnelse med kompromiss mellom interesser.']]);
add('navigasjonshjulet','Navigasjonshjulet','ledelse','Seks innfallsvinkler til å undersøke et vanskelig handlingsvalg.',
'Hjulet skiller juridiske, identitetsmessige, moralske, omdømmemessige, økonomiske og etiske spørsmål. Det hjelper med å oppdage spenninger, men gir ingen automatisk totalscore eller fasit. Lovlighet, lønnsomhet og popularitet er ulike vurderinger.',
'Jus: er handlingen lovlig?|Identitet: passer den med hvem vi vil være?|Moral: stemmer den med det vi oppfatter som riktig?|Omdømme: hva gjør den med tilliten til oss?|Økonomi: er den økonomisk forsvarlig?|Etikk: kan den begrunnes prinsipielt overfor andre?',[ref(5,13)],
'En innkjøpsleder får tilbud om en kostbar reise fra en leverandør. Hun undersøker først hvilke regler som gjelder, uten å anta at en hyggelig invitasjon er uproblematisk. Identitetsspørsmålet er om deltakelse passer med virksomhetens løfte om uavhengighet. Moralsk kjenner hun ubehag ved å motta en personlig fordel fra en tilbyder.\n\nOmdømmeperspektivet spør hvordan andre leverandører og offentligheten ville forstå reisen. Økonomisk vurderer hun læringsutbyttet opp mot kostnadene ved et alternativ virksomheten betaler selv. Etisk undersøker hun likebehandling, interessekonflikter og om begrunnelsen tåler å bli offentlig. Hun velger et uavhengig fagseminar. Hjulet synliggjør hvorfor «det er billig for oss» ikke alene avgjør saken; eksemplet gir ikke en juridisk konklusjon om en faktisk invitasjon.',
[['etisk-ledelse',.93,'Hjulet konkretiserer lederens etiske refleksjon.'],['omdoemme',.87,'Omdømme er én dimensjon og må skilles fra etisk forsvarlighet.'],['konsekvensetikk',.86,'Konsekvensvurdering inngår, men suppleres av flere begrunnelsestyper.'],['pliktetikk',.86,'Prinsipper og grenser utfyller vurderinger av nytte.']]);
add('samfunnsansvar','Samfunnsansvar (CSR)','maal-strategi','Virksomhetens ansvar for hvordan dens handlinger påvirker mennesker, samfunn og omgivelser.',
'Forelesningene drøfter økonomisk, juridisk, etisk og filantropisk ansvar. Perspektivet går utover kortsiktig egeninteresse og kobler strategi til berørte parter. Gaver eller positive kampanjer opphever ikke ansvar for skade i den ordinære driften.',
'Økonomisk ansvar: opprettholde en levedyktig virksomhet.|Juridisk ansvar: forholde seg til relevante krav.|Etisk ansvar: vurdere forsvarlig handling også utover minimumskrav.|Filantropisk ansvar: frivillige bidrag til fellesskapet.',[ref(5,11,12),ref(6,23)],
'En klesprodusent vurderer en rimeligere underleverandør. Økonomisk trenger den lønnsom drift for å kunne betale ansatte og fortsette produksjonen. Juridisk undersøker den relevante krav og kontrakter. Etisk vurderer den arbeidsforhold og miljøbelastning selv der kontrollen er svak eller minstekravene lave. Den følger opp informasjon og forbedringstiltak i leverandørkjeden.\n\nSelskapet støtter også et lokalt gjenbruksverksted som et frivillig samfunnsbidrag. Dette filantropiske tiltaket erstatter ikke arbeidet med leverandørene. Hvis bedriften bare fremhever gaven i markedsføringen, mens skadelig praksis fortsetter, oppstår et gap mellom omdømmebygging og faktisk ansvar. En drøfting kan derfor sammenholde økonomisk bærekraft, interessentkrav og konsistens mellom ord og handling.',
[['interessentmodellen',.94,'Samfunnsansvar vurderes overfor parter som påvirker og påvirkes av virksomheten.'],['institusjonelle-omgivelser',.9,'Regler og samfunnsforventninger påvirker hva som regnes som ansvarlig drift.'],['institusjonelle-strategier',.89,'Reelle tiltak kan sammenlignes med symbolsk konformitet.']]);
add('destruktiv-ledelse','Destruktiv ledelse','ledelse','Lederatferd og samspill som undergraver medarbeidere eller virksomhetens legitime interesser.',
'Den giftige trekanten retter oppmerksomheten mot samspillet mellom destruktive ledere, mottakelige eller medvirkende følgere og en muliggjørende kontekst. Forklaringen skal ikke legge ansvaret for krenkelser på den utsatte. Svak kontroll, maktavhengighet og frykt kan gjøre skadelig praksis vanskelig å utfordre.',
'Leder: skadelig maktbruk, manipulering eller systematisk nedvurdering.|Følgere: avhengighet, frykt eller egeninteresse kan opprettholde mønsteret.|Kontekst: svake kontrollordninger og normer kan tillate atferden.|Forebygging må omfatte ansvar, innsyn og mulighet til å si fra.',[ref(5,41),ref(14,29,31)],
'En avdelingsleder latterliggjør medarbeidere som rapporterer avvik og belønner dem som skjuler problemer. Dette er lederdelen av trekanten. Noen ansatte tier av frykt for å miste vakter, mens en liten gruppe støtter lederen fordi de får fordeler: følgerdelen. Toppledelsen ser bare på salgstall og har ingen uavhengig kanal for kritikk: konteksten.\n\nEn forklaring som bare sier at lederen har en vanskelig personlighet, overser hvordan praksisen beskyttes. Virksomheten må undersøke handlingene, beskytte muligheten til å si fra og endre kontroll- og belønningsordningene. Medarbeidernes avhengighet forklarer taushet, men gjør dem ikke ansvarlige for å bli utsatt. Vanlig saklig uenighet eller en upopulær, begrunnet beslutning er ikke alene bevis på destruktiv ledelse.',
[['maktformer',.92,'Skadelig ledelse kan virke gjennom både åpen og skjult makt.'],['etisk-ledelse',.94,'En viktig kontrast om ansvar, verdighet og varsling.'],['karismatisk-ledelse',.81,'Personlig tiltrekning kan kombineres med skadelig maktbruk, men karisma er ikke i seg selv destruktiv.']]);
add('jobbholdninger','Jobbholdninger (ABC)','motivasjon','Vurderende innstillinger til arbeidet som omfatter følelser, forestillinger og handlingsberedskap.',
'ABC-modellen skiller affektive, atferdsorienterte og kognitive sider ved holdninger. En uttrykt holdning er ikke en sikker prediksjon av faktisk handling, fordi situasjonen og handlingsmulighetene også virker inn. Holdninger til en bestemt jobb må skilles fra mer generelle verdier og personlighetstrekk.',
'Affekt: hva personen føler overfor arbeidet.|Atferdskomponent: hensikter og tilbøyelighet til å handle.|Kognisjon: oppfatninger og vurderinger.|Faktisk atferd påvirkes også av rammer og muligheter.',[ref(14,2,4),ref(9,11,14)],
'En ansatt misliker et nytt journalsystem. Hun føler frustrasjon når skjermbildene låser seg: affekt. Hun mener systemet fører til flere dobbeltregistreringer: kognisjon. Hun har lyst til å unngå systemet og foreslår å gå tilbake til det gamle: handlingsberedskap. Likevel bruker hun det fordi alle saker må registreres der.\n\nLederen skiller derfor mellom følelsen, påstanden om feil og hva den ansatte faktisk gjør. Teamet undersøker registreringstiden og prøver en enklere arbeidsflyt. Når problemene reduseres, kan holdningen endre seg. Eksemplet viser hvorfor lydig bruk ikke nødvendigvis betyr positiv holdning, og hvorfor motvilje mot ett system ikke gir grunnlag for å stemple personen som generelt negativ eller lite endringsvillig.',
[['organisasjonsatferd',.94,'Holdninger er én del av sammenhengen mellom tenkning, følelser og handling.'],['endringsmotstand',.85,'Holdninger kan gi innsikt i reaksjoner på endring uten å sidestilles med motstand.']]);
add('jobbtilfredshet','Jobbtilfredshet','motivasjon','Den ansattes vurdering av hvor tilfredsstillende jobben eller sider ved den oppleves.',
'Tilfredshet kan vurderes samlet og for enkeltområder som oppgaver, ledelse, lønn og kolleger. Avvik mellom det man ønsker og det man opplever, avhenger også av hvor viktig området er. Tilfredshet, jobbengasjement og tilknytning til organisasjonen er ulike begreper. Sammenhengen med prestasjon kan gå begge veier eller skyldes andre forhold.',
'Skill samlet tilfredshet fra tilfredshet med bestemte forhold.|Vurder gapet mellom ønsket og opplevd situasjon.|Betydningen av et forhold varierer mellom personer.|Ikke slutte fra samvariasjon til at trivsel alene skaper produktivitet.',[ref(14,5,10)],
'Sara liker kollegene og arbeidsoppgavene, men er misfornøyd med uforutsigbare vakter. Jonas har samme turnus og opplever den som fleksibel. En samlet trivselsskår kan skjule at de vurderer samme forhold ulikt. For Sara er forutsigbarhet særlig viktig, så gapet mellom ønsket og faktisk turnus trekker tilfredsheten sterkt ned.\n\nNår teamet får en mer forutsigbar plan, øker både tilfredshet og kvalitet. Lederen konkluderer likevel ikke med at tilfredshet alene forårsaket forbedringen: bedre bemanning kan ha påvirket begge, og det å lykkes faglig kan også øke tilfredsheten. Sara kan samtidig være glad i jobben uten å være sterkt knyttet til akkurat denne arbeidsgiveren. Eksemplet holder begrepene og mulige årsaksretninger atskilt.',
[['herzberg',.93,'Tofaktorteorien skiller forhold som skaper tilfredshet fra forhold som forebygger mistrivsel.'],['organisatorisk-tilknytning',.88,'Tilfredshet med jobben og bånd til organisasjonen kan samvariere, men er forskjellige.'],['produktivitet-effektivitet',.76,'Forholdet mellom tilfredshet og ytelse må drøftes uten enkel kausal slutning.']]);
add('psykologisk-kontrakt','Psykologisk kontrakt','motivasjon','Opplevde gjensidige forpliktelser mellom medarbeider og arbeidsgiver, utover den formelle kontrakten.',
'Forventningene er subjektive og kan være ulike på hver side. Transaksjonelle kontrakter gjelder mer avgrensede bytter, mens relasjonelle kontrakter omfatter langsiktig tillit, lojalitet og utvikling. Opplevd kontraktsbrudd kan påvirke tillit og reaksjoner på endring selv om ingen formell avtale er brutt.',
'Skill juridisk arbeidsavtale fra subjektivt opplevde løfter.|Transaksjonelt: konkrete, avgrensede ytelser og gjenytelser.|Relasjonelt: langsiktige og mer åpne forpliktelser.|Avklar forventninger og undersøk hva partene mener er lovet.',[ref(14,12,13)],
'Da Amir begynte, sa lederen at bedriften «satser på folk som vil utvikle seg». Amir tolket det som et løfte om fagkurs og en langsiktig karriere mot lojal innsats. Lederen mente bare at kurs kunne vurderes når budsjettet tillot det. Den formelle kontrakten regulerer lønn og arbeidstid, men løser ikke dette tolkningsgapet.\n\nDa alle kurs kuttes under en omorganisering, opplever Amir kontraktsbrudd og blir mindre villig til å bidra utover stillingen. Det relasjonelle båndet svekkes. Han begynner å forstå forholdet mer transaksjonelt: avtalte timer mot lønn. En samtale må avklare hvilke løfter som faktisk ble gitt og hvilke forventninger som kan innfris. At ledelsen ikke mente å love noe, fjerner ikke automatisk hans opplevelse.',
[['endringsmotstand',.94,'Opplevd kontraktsbrudd kan forklare motstand og tap av tillit ved endring.'],['lmx',.9,'Gjensidige forventninger og tillit står sentralt i leder–medarbeider-relasjonen.'],['organisatorisk-tilknytning',.91,'Opplevde forpliktelser kan styrke eller svekke båndet til arbeidsgiver.']]);
add('psykososialt-arbeidsmiljo','Psykososialt arbeidsmiljø','motivasjon','Psykologiske og sosiale sider ved arbeidets organisering og samspillet mellom mennesker.',
'Belastningsperspektivet undersøker stress, uklare roller, konflikt og krenkelser. Berikelsesperspektivet undersøker støtte, mening, medvirkning, læring og engasjement. Perspektivene utfyller hverandre: fravær av problemer er ikke alene et godt utviklingsmiljø. Organisatoriske forhold må undersøkes sammen med personers erfaringer.',
'Kartlegg krav, roller, relasjoner og ressurser.|Reduser belastende forhold fremfor bare å be ansatte tåle mer.|Bygg støtte, mestring, innflytelse og utviklingsmuligheter.|Skill saklig uenighet fra gjentatte negative handlinger og maktubalanse.|Følg opp tiltak på individ-, gruppe- og organisasjonsnivå.',[ref(14,13,14),ref(14,29,37)],
'Et kundesenter har høyt fravær og lite læring. Kartlegging viser både for mange saker, motstridende beskjed fra to ledere og en praksis der feil møtes med latterliggjøring. Belastningsperspektivet retter tiltak mot saksmengde, rolleavklaring og uakseptabel samhandling. Lederen undersøker konkrete hendelser fremfor å kalle de ansatte lite robuste.\n\nBerikelsesperspektivet gir andre tiltak: felles problemløsning, tid til opplæring og innflytelse over arbeidsrekkefølgen. Teamet følger med på arbeidsmengde, opplevd støtte og læring over tid. Et sosialt arrangement alene ville ikke rettet opp den uklare organiseringen. Samtidig er lavere fravær ikke nok til å vite at jobben oppleves meningsfull. Begge perspektivene trengs for å vurdere miljøet.',
[['hackman-oldham',.91,'Jobbutforming kan både skape ressurser og redusere belastninger.'],['destruktiv-ledelse',.92,'Skadelig lederatferd inngår i belastningsperspektivet.'],['matrisestruktur',.77,'Dobbelt lederskap kan gi rolleuklarhet når ansvar og prioriteringer ikke avklares.']]);
add('jobbstress','McGrath: jobbstress','motivasjon','En prosess der krav, tolkning, reaksjoner og konsekvenser virker sammen i forholdet mellom person og miljø.',
'McGraths transaksjonsperspektiv ser stress som samspill, ikke bare som en egenskap ved jobben eller personen. Vurderingen av krav og egne mestringsmuligheter er sentral. Belastninger kan komme fra oppgaver, roller, relasjoner og andre livsarenaer. Krav må ses sammen med kontroll og støtte. Modellen brukes her til organisasjonsanalyse, ikke diagnostisering.',
'Krav: belastninger og utfordringer i situasjonen.|Tolkning: hvordan krav og mestringsmuligheter vurderes.|Respons: følelsesmessige, kroppslige eller atferdsmessige reaksjoner.|Konsekvenser: følger for person og organisasjon, med tilbakevirkning på prosessen.|Støtte kan være emosjonell, oppgaverettet, informativ og praktisk.',[ref(14,14,20),ref(9,28,36)],
'En ny saksbehandler får dobbelt så mange saker samtidig som rutinene endres: krav. Hun tolker dette som at hun må klare alt alene og frykter å gjøre feil: tolkning. Hun blir urolig, hopper mellom saker og spør mindre om hjelp: respons. Flere saker må gjøres om, og køen vokser: konsekvens som igjen øker kravene.\n\nLederen reduserer saksmengden og avklarer prioriteringer i stedet for bare å oppfordre til positiv tenkning. En kollega lytter og viser omsorg, hjelper med å sortere oppgaver, forklarer de nye rutinene og overtar noen saker. Dette illustrerer fire former for støtte. Den samme arbeidsmengden kan oppleves annerledes av en erfaren kollega, men det fritar ikke organisasjonen fra å undersøke om kravene er forsvarlige.',
[['psykososialt-arbeidsmiljo',.96,'Stressprosessen utdyper belastningsperspektivet.'],['begrenset-rasjonalitet',.82,'Tidspress og belastning kan innsnevre oppmerksomhet og alternativsøk.'],['endringsmotstand',.84,'Dobbeltarbeid og usikkerhet kan gi forståelige reaksjoner på endring.']]);
add('jobbengasjement','Jobbengasjement','motivasjon','En positiv arbeidsrelatert tilstand preget av energi, dedikasjon og oppslukthet.',
'Engasjement beskriver hvordan man investerer seg i selve arbeidet. Det er forskjellig fra tilfredshet med arbeidsforholdene og lojalitet til arbeidsgiveren. Ressurser, meningsfulle utfordringer og sosialt samspill kan støtte engasjement. Høyt engasjement opphever ikke behov for grenser og restitusjon.',
'Vigør: energi og utholdenhet i arbeidet.|Dedikasjon: opplevd betydning, entusiasme og involvering.|Absorpsjon: konsentrasjon og oppslukthet.|Vurder arbeidskrav sammen med tilgjengelige ressurser.',[ref(14,33,36),ref(9,53,59)],
'Et team utvikler bedre veiledning for nye studenter. Liv møter opp med energi og fortsetter å arbeide med vanskelige problemer: vigør. Hun opplever at tjenesten gjør studiestarten tryggere og snakker engasjert om formålet: dedikasjon. Når hun tester og forbedrer veiledningen, blir hun dypt konsentrert: absorpsjon.\n\nEngasjementet støttes av tid, faglig sparring og frihet til å prøve løsninger. Lederen følger samtidig opp arbeidsmengden, slik at entusiasmen ikke blir en forventning om ubegrenset overtid. Liv kan være svært engasjert i oppgaven selv om hun vurderer jobb hos en annen arbeidsgiver. Eksemplet viser derfor hvorfor engasjement ikke er det samme som organisasjonstilknytning, og hvorfor ressurser må følge ambisjonene.',
[['indre-ytre-motivasjon',.91,'Interesse og mening kan støtte engasjement, men begrepene er ikke identiske.'],['jobbtilfredshet',.89,'Engasjement innebærer aktivering og involvering, mens tilfredshet er en vurdering av jobben.'],['hackman-oldham',.91,'Meningsfulle oppgaver, autonomi og tilbakemelding gir en naturlig forklaring på engasjement.']]);
add('psykologisk-kapital','Luthans: psykologisk kapital','motivasjon','Utviklingsbare psykologiske ressurser i form av mestringstro, håp, optimisme og resiliens.',
'Perspektivet undersøker positive ressurser som kan støtte arbeid og håndtering av utfordringer. Håp omfatter både drivkraft og alternative veier mot mål. Resiliens handler om å komme videre etter motgang. Individuelle ressurser supplerer gode arbeidsbetingelser; de skal ikke brukes som erstatning for å rette opp urimelige krav.',
'Mestringstro: tro på å kunne håndtere en konkret utfordring.|Håp: målrettet drivkraft og mulige veier fremover.|Optimisme: forventning om positive muligheter med rom for realisme.|Resiliens: evne til å hente seg inn og tilpasse seg etter motgang.',[ref(14,35,36),ref(9,37)],
'Et team får avslag på sin første prosjektplan. Nora har løst lignende oppgaver før og tror hun kan mestre revisjonen: mestringstro. Hun beholder målet om en bedre tjeneste og lager to alternative fremgangsmåter: håp. Hun forventer at teamet kan få til forbedringer, men undersøker hvorfor planen ble avslått: realistisk optimisme.\n\nEtter skuffelsen tar hun imot støtte, justerer planen og kommer tilbake i arbeidet: resiliens. Lederen bidrar med tid, avklaringer og konkret tilbakemelding, ikke bare en appell om å være positiv. De fire ressursene virker sammen, men er analytisk forskjellige. Hvis budsjettet faktisk ikke tillater prosjektet, er det ansvarlig å endre målet; psykologisk kapital betyr ikke å overse realiteter.',
[['jobbengasjement',.93,'Psykologiske ressurser kan støtte energi, dedikasjon og konsentrasjon.'],['maalsettingsteori',.88,'Mestringstro og alternative målveier er relevante for målrettet innsats.'],['sosial-laering',.8,'Observasjon, mestringserfaring og støtte gir en naturlig læringsbro.']]);
add('organisatorisk-rettferdighet','Adams og rettferdighet','motivasjon','Hvordan ansatte vurderer fordeling, beslutningsprosedyrer og måten de blir behandlet på.',
'Adams’ likeverdsteori gjelder sammenligning av eget forhold mellom bidrag og utbytte med relevante andre. Den bredere rettferdighetslitteraturen skiller også mellom prosedyrene som skaper fordelingen og den mellommenneskelige behandlingen. Lik lønn er ikke automatisk opplevd rettferdighet, og ulik lønn er ikke automatisk urettferdig når relevante bidrag er ulike.',
'Fordeling: hvordan bidrag og utbytte sammenlignes.|Referanser kan være eget tidligere arbeid eller andre, internt eller eksternt.|Prosedyrer: konsistens, upartiskhet, informasjon, korrigerbarhet, representativitet og etikk.|Samhandling: respekt, verdighet og begrunnelser.|Opplevd ubalanse kan føre til endret innsats, krav, ny sammenligning eller avgang.',[ref(15,23,27)],
'To rådgivere oppdager en lønnsforskjell. Anna sammenligner lønn med erfaring, ansvar og innsats, ikke bare beløpet: fordelingsrettferdighet og likeverd. Hun sammenligner også med sin forrige jobb og andre rådgivere utenfor virksomheten, og referansevalget påvirker vurderingen.\n\nLederen legger frem kriterier som er brukt likt over tid, kontrollerer opplysningene, unngår egeninteresser, hører begge og tilbyr korrigering. Dette konkretiserer prosedyrerettferdighet. Han forklarer vurderingen respektfullt, uten å ydmyke noen: samhandlingsrettferdighet. Hvis Anna fortsatt opplever ubalanse, kan hun be om høyere lønn, redusere ekstraarbeid, endre sammenligningsgrunnlag eller søke ny jobb. En rettferdig prosess kan styrke tillit selv når hun ikke får hele ønsket innfridd, men den gjør ikke enhver fordeling forsvarlig.',
[['beloenningssystemer',.95,'Belønning må vurderes ut fra både fordeling og prosedyre.'],['endringsgjennomfoering',.89,'Rettferdig prosess og medvirkning er viktig ved omstilling.'],['etisk-ledelse',.91,'Respekt og upartisk behandling forbinder motivasjon med lederetikk.'],['konflikt-beslutningskvalitet',.83,'Opplevd urettferdighet kan flytte saklig uenighet over i destruktiv konflikt.']]);
add('mcclelland-behov','McClelland: tre behov','motivasjon','En behovstilnærming som skiller prestasjon, tilhørighet og makt som motivasjonskilder.',
'Mennesker kan ha ulike styrker og kombinasjoner av de tre behovene. Prestasjonsbehov retter seg mot mestring og resultater, tilhørighet mot relasjoner og aksept, og makt mot innflytelse. Makt kan brukes til egen fordel eller til felles mål. Behovene er fortolkningsverktøy, ikke merkelapper som alene bestemmer atferd.',
'Prestasjon: utfordringer, ansvar og tilbakemelding på mestring.|Tilhørighet: fellesskap og gode relasjoner.|Makt: mulighet til å påvirke andre og hendelser.|Undersøk kombinasjoner og situasjon fremfor å tilordne én fast type.',[ref(15,8,9)],
'Tre medarbeidere deltar i et forbedringsprosjekt. Eva ønsker et krevende, men oppnåelig delmål og konkrete målinger av fremdrift: prestasjonsbehov. Omar motiveres av tett samarbeid og av at gruppen fungerer godt: tilhørighetsbehov. Ingrid ønsker å påvirke prioriteringene og få støtte til en ny arbeidsmåte: maktbehov.\n\nLederen gir Eva faglige utfordringer, sørger for samarbeidsarenaer og gir Ingrid et tydelig mandat med ansvarlighet. Samtidig kan Eva ønske anerkjennelse fra gruppen og Omar ønske innflytelse. Ingrid kan bruke makten til å styrke teamet eller til å fremheve seg selv. Eksemplet viser variasjon i drivkrefter uten å gjøre mennesker til entydige typer eller anta at ett behov alltid er best.',
[['maslow',.87,'To ulike måter å systematisere behov på.'],['maktbaser',.79,'Ønske om innflytelse må skilles fra ressursene som faktisk gir makt.'],['maalsettingsteori',.86,'Prestasjonsbehov kan knyttes til utfordring, ansvar og tilbakemelding.']]);
add('regulatorisk-fokus','Regulatorisk fokus','motivasjon','Forskjellen mellom å orientere seg mot fremgang og gevinster eller trygghet og å unngå tap.',
'Promoteringsfokus legger vekt på ambisjoner og muligheter. Preventeringsfokus legger vekt på plikter, sikkerhet og å forebygge feil. Både person og situasjon kan påvirke fokuset. Det er ikke en rangering der den ene orienteringen alltid er bedre.',
'Promotering: oppnå ønskede gevinster og utvikling.|Preventering: ivareta ansvar og unngå uønskede tap.|Oppgave og innramming kan påvirke hvilket fokus som aktiveres.|Begge perspektivene kan være nødvendige i samme prosjekt.',[ref(15,9,10)],
'Et team utvikler en digital søknadstjeneste. Produktansvarlig spør hvilke nye muligheter som kan gjøre tjenesten enklere: promoteringsfokus. Kvalitetsansvarlig spør hvilke feil som kan skade brukere, og hvilke kontroller som må fungere: preventeringsfokus. Begge bidrar til den samme leveransen.\n\nI idéfasen inviterer lederen til flere mulige løsninger. Før lansering legger hun større vekt på å oppdage feil og sikre at grunnleggende krav er oppfylt. Dette betyr ikke at én person alltid er kreativ og den andre alltid er forsiktig; samme medarbeider kan skifte fokus med oppgaven. En drøfting bør undersøke når fremgangsorientering åpner muligheter, og når forebyggende orientering beskytter viktige hensyn.',
[['maalsettingsteori',.87,'Mål kan rammes inn som fremgang eller forebygging.'],['march-utnyttelse-utforsking',.78,'Orienteringene kan belyse spenningen mellom utprøving og pålitelig drift uten å være samme modell.']]);
add('prososial-motivasjon','Prososial motivasjon','motivasjon','Ønske om å gjøre en positiv forskjell for andre gjennom arbeidet.',
'Motivasjonen retter seg mot mottakerens nytte. Den kan kombineres med interesse for oppgaven eller ytre belønning, men er analytisk forskjellig fra begge. Å ville hjelpe garanterer ikke at hjelpen faktisk virker, og sterke hjelpeidealer kan komme i konflikt med kapasitet og grenser.',
'Spør hvem arbeidet skal være nyttig for.|Skill mottakerens nytte fra egen glede ved aktiviteten.|Undersøk om innsatsen faktisk møter mottakerens behov.|Kombiner hjelpevillinghet med ansvarlige grenser.',[ref(8,8),ref(15,28,29)],
'En rådgiver bruker tid på å gjøre et komplisert skjema forståelig for brukere. Hun synes selve tekstredigeringen er nokså kjedelig, men blir motivert av at flere skal kunne søke uten hjelp. Det viser prososial motivasjon uten nødvendigvis sterk indre interesse for aktiviteten. En kollega liker språkoppgaven i seg selv; de to motivene kan også finnes samtidig.\n\nRådgiveren tester teksten med brukere og oppdager at et «hjelpsomt» tillegg gjorde skjemaet lengre og vanskeligere. Hun fjerner det. Når etterspørselen øker, avtaler teamet arbeidsdeling og tidsgrenser, slik at ønsket om å hjelpe ikke blir ubegrenset merarbeid. God intensjon, oppgavelyst og faktisk nytte må vurderes hver for seg.',
[['indre-ytre-motivasjon',.93,'Mottakerorientert motivasjon må skilles fra interesse i aktiviteten og ytre konsekvenser.'],['tjenende-ledelse',.92,'Andres utvikling og velferd er en naturlig motivasjonsbro.'],['hackman-oldham',.87,'Opplevd betydning for andre kan gjøre arbeidet meningsfullt.']]);
add('thorsrud-jobbkrav','Thorsrud: psykologiske jobbkrav','motivasjon','Prinsipper for arbeidsinnhold som ivaretar læring, innflytelse, fellesskap og utvikling.',
'De seks psykologiske jobbkravene inngår i en tradisjon for demokrati i arbeidslivet og sammenheng mellom sosial og teknisk organisering. De beskriver kvaliteter ved arbeidet, ikke bare krav om at arbeidstakeren skal prestere mer.',
'Et rimelig nivå av utfordring og variasjon.|Mulighet til å lære og fortsette å lære.|Et område der man kan treffe beslutninger selv.|Anerkjennelse og mellommenneskelig støtte.|Sammenheng mellom arbeidet og en meningsfull større helhet.|En ønsket fremtid med utviklingsmuligheter.',[ref(15,32,33),ref(8,40)],
'Et verksted lar ikke lenger hver ansatt utføre én bevegelse hele dagen. Arbeidet veksler mellom feilsøking, reparasjon og kontroll: variasjon og utfordring. Ansatte får opplæring og tid til å lære nye produkter: læring. Teamet bestemmer arbeidsrekkefølgen innen avtalte sikkerhetsrammer: eget beslutningsområde.\n\nKollegene hjelper hverandre og gir anerkjennelse for godt arbeid: sosial støtte. De møter kunder og ser hvordan reparasjonen forlenger produktets levetid: meningsfull sammenheng. En plan for videre fagutvikling gjør det mulig å se en ønsket fremtid i jobben. Tiltakene må utformes sammen med de ansatte og med nødvendig bemanning. Bare å legge flere oppgaver til en allerede presset jobb oppfyller ikke intensjonen.',
[['hackman-oldham',.95,'Begge belyser motiverende jobbutforming, med ulike begreper og historisk innramming.'],['bemyndiggjoring',.91,'Eget beslutningsområde og medvirkning gjelder faktisk innflytelse.'],['psykososialt-arbeidsmiljo',.93,'Jobbkravene konkretiserer berikelsesperspektivet.']]);
add('gruppetenkning','Gruppetenkning','kultur','Når press mot enighet svekker gruppens kritiske vurdering av alternativer og risiko.',
'Sterkt samhold kan støtte samarbeid, men kan også gjøre uenighet kostbar. Overvurdering av gruppen, lukkethet og konformitetspress kan snevre inn informasjonsgrunnlaget. Gruppetenking er ikke det samme som enhver enighet; spørsmålet er hvordan enigheten ble til og hva som ble utelatt.',
'Overvurdering av egen gruppes evner og riktighet.|Lukkethet for motargumenter og eksterne perspektiver.|Selvsensur og press på dem som er uenige.|Åpen kritikk, alternative løsninger og eksterne blikk kan motvirke mønsteret.',[ref(7,27,30)],
'En ledergruppe er stolt av tidligere suksess og vil lansere et nytt produkt raskt. De sier at «vi kjenner markedet best»: overvurdering. En kritisk kunderapport avvises som lite representativ uten undersøkelse: lukkethet. En analytiker slutter å stille spørsmål etter å ha blitt kalt negativ: konformitetspress og selvsensur.\n\nMøtereferatet sier at alle støtter lanseringen, men enigheten bygger på filtrert informasjon. Gruppen ber derfor et uavhengig team undersøke risiko, vurderer et alternativ med begrenset pilot og lar lederen uttale seg sist. Tiltakene kan forbedre diskusjonen, men garanterer ikke riktig beslutning. Poenget er å bevare faglig prøving, ikke å skape personlig konflikt eller være uenig for enhver pris.',
[['begrenset-rasjonalitet',.92,'Konformitet kan ytterligere begrense informasjon og alternativsøk.'],['konflikt-beslutningskvalitet',.94,'Saklig meningsbrytning er en viktig kontrast til undertrykt uenighet.'],['kommunikativ-rasjonalitet',.91,'Fri argumentasjon utfordres når rang og gruppepress avgjør hva som kan sies.']]);
add('transaksjonskostnader','Transaksjonskostnader','maal-strategi','Kostnader ved å etablere, avtale, koordinere og følge opp utveksling mellom aktører.',
'En tjenestes pris er ikke hele kostnaden ved å kjøpe den. Søk etter leverandører, forhandlinger, kontroll og håndtering av uenighet inngår også. Perspektivet brukes til å sammenligne markedskjøp, samarbeid og intern organisering. Intern drift har egne styringskostnader og er ikke automatisk best.',
'Søk og innhenting av informasjon.|Forhandling og utforming av avtaler.|Kontroll, oppfølging og tilpasning.|Sammenlign samlet kostnad og kvalitet ved ulike organiseringsformer.',[ref(6,21)],
'Et firma vurderer å sette kundestøtten ut til en leverandør med lav timepris. Før avtalen må det kartlegge kandidater og kontrollere kompetanse: søkekostnader. Deretter brukes tid på servicenivå, ansvar og endringsvilkår: forhandlingskostnader. Under driften må firmaet måle kvalitet og løse uenighet om vanskelige saker: oppfølgingskostnader.\n\nDen lave prisen kan derfor bli mindre attraktiv enn den først så ut. Firmaet sammenligner med intern drift, som også krever ledelse, opplæring og koordinering, og med en delt løsning der spesialsaker beholdes internt. Analysen handler om samlet organisering, ikke bare fakturabeløpet. Kvalitet og avhengighet av leverandøren må tas med før man velger.',
[['interorganisatoriske-relasjoner',.94,'Kontrakter og samarbeid har kostnader ved etablering og oppfølging.'],['haandtere-tekniske-omgivelser',.86,'Integrasjon og samarbeid kan vurderes som alternative måter å håndtere avhengighet på.'],['byttemakt',.83,'Få alternative leverandører kan påvirke både forhandling og kostnader.']]);
add('erfaringslaering','Erfaringslæring','laering','Læring som kobler konkret erfaring, refleksjon, begrepsutvikling og ny utprøving.',
'Erfaring blir ikke automatisk til læring. Aktøren må undersøke hva som skjedde, utvikle en forklaring og prøve den i praksis. En læringssirkel kan starte på ulike steder og gjentas. På organisasjonsnivå må innsikten også deles og få betydning for felles arbeidsmåter.',
'Oppleve og observere en konkret hendelse.|Reflektere over forløp og alternative forklaringer.|Formulere en mer generell forståelse.|Prøve forståelsen i en ny handling og undersøke utfallet.',[ref(12,8)],
'Et team opplever at en workshop gir få innspill fra brukerne: konkret erfaring. Etterpå undersøker de hvem som snakket, hvordan spørsmålene ble stilt, og om tidspunktet passet: refleksjon. De utvikler en hypotese om at små grupper med konkrete oppgaver gir flere mulighet til å delta: begrepsutvikling.\n\nI neste workshop prøver de dette og registrerer både deltakelse og kvaliteten på innspillene: utprøving. Hvis resultatet fortsatt er svakt, vurderer de andre forklaringer i en ny runde. Når funnene dokumenteres og blir del av planleggingen for flere team, kan individuell erfaring bli organisatorisk læring. Én vellykket workshop er et læringsgrunnlag, ikke et sikkert bevis på at metoden alltid virker.',
[['organisatorisk-laering',.94,'Erfaringssirkelen utdyper forbindelsen mellom innsikt og handling.'],['argyris-laeringskretser',.91,'Refleksjon kan rette seg mot både arbeidsmåter og underliggende mål.'],['toyota-hvorfor',.85,'Systematisk årsaksundersøkelse kan inngå i refleksjonsfasen.']]);

add('alderfer-erg','Alderfer: ERG','motivasjon','En behovsmodell med eksistens, relasjoner og vekst, der flere behov kan virke samtidig.',
'ERG sammenfatter behov i tre grupper og åpner for bevegelse begge veier. Når vekstmuligheter blokkeres, kan personen rette mer oppmerksomhet mot relasjoner eller materielle betingelser. Dette kalles frustrasjon–regresjon. Modellen er en fortolkningsramme, ikke en sikker regel for hvordan alle reagerer.',
'Eksistens: materielle og grunnleggende betingelser.|Relasjoner: kontakt, tilhørighet og gjensidig anerkjennelse.|Vekst: utvikling og bruk av egne evner.|Flere behov kan være aktive samtidig.|Frustrasjon på ett område kan øke oppmerksomheten mot andre behov.',[ref(15,7)],
'En medarbeider ønsker forutsigbar inntekt og gode arbeidsbetingelser: eksistens. Hun ønsker også et støttende fagmiljø: relasjoner, og krevende oppgaver som utvikler kompetansen: vekst. Behovene virker samtidig, selv om vekten varierer.\n\nNår utviklingsoppgavene gjentatte ganger blir avlyst, begynner hun å legge større vekt på lønn og sosial tilhørighet. Dette kan illustrere frustrasjon–regresjon. Lederen bør likevel undersøke hennes egen forklaring fremfor å anta mekanismen. Mer lønn kan være verdifullt, men løser ikke automatisk manglende utvikling. Sammenlignet med en rigid lesning av Maslows trapp åpner ERG tydeligere for overlapp og bevegelse mellom behovsområder.',
[['maslow',.95,'ERG gir en nær sammenligning av behovsgrupper, samtidighet og frustrasjon–regresjon.'],['mcclelland-behov',.87,'Begge nyanserer behovsmotivasjon med ulike grupperinger.'],['karrieresystemer',.84,'Blokkerte utviklingsmuligheter kan drøftes som frustrerte vekstbehov.']]);

export const updates=[
 ['produktivitet-effektivitet',[ref(6,18)],'Produktivitet beskriver forholdet mellom produsert output og ressursinnsats. Effektivitet vurderer ressursbruk i lys av måloppnåelse: om organisasjonen skaper de ønskede resultatene. Flere behandlede saker per time kan derfor være høyere produktivitet uten bedre effektivitet dersom kvaliteten eller formålet svekkes.',null],
 ['formelle-uformelle-trekk',[ref(13,5),ref(13,12),ref(13,17,19)],'Formelle trekk omfatter vedtatte mål, strategi, arbeidsdeling og beslutningsrettigheter. Struktur kan beskrives gjennom horisontal differensiering mellom oppgaver, vertikal differensiering mellom nivåer, kontrollspenn og formalisering av regler. Uformelle trekk omfatter blant annet kultur, relasjoner og makt som former faktisk atferd. Et organisasjonskart viser derfor ikke hele organisasjonen.',null],
 ['styringsmekanismer',[ref(13,29,30),ref(7,36,39)],'Organisasjonen kan påvirke atferd gjennom rekruttering, sosialisering, disiplinering og kontroll. Sosialisering innebærer at nye medlemmer lærer oppgaver, roller, kulturelle forventninger og sosiale relasjoner. Mekanismene virker sammen og kan sende motstridende signaler. Kontroll av målbare resultater kan for eksempel undergrave en norm om grundig hjelp dersom bare antall saker belønnes.',null],
 ['cameron-quinn',[ref(7,25)],'Rammeverket organiserer konkurrerende verdier langs to akser: fleksibilitet versus stabilitet/kontroll, og internt versus eksternt fokus. Klan kombinerer internt fokus og fleksibilitet; hierarki internt fokus og kontroll; adhockrati eksternt fokus og fleksibilitet; marked eksternt fokus og kontroll. Virksomheter kan ha blandinger og ulike subkulturer.',null],
 ['etisk-ledelse',[ref(5,6,9),ref(5,14)],'Etisk ledelse handler om å begrunne og praktisere ansvarlig handling, være rollemodell og skape ordninger som gjør det mulig å ta opp dilemmaer og si fra. Moral viser til oppfatninger og praksis om rett og galt; etikk innebærer systematisk refleksjon over slike vurderinger. Personlige verdier, lovlighet, omdømme og lønnsomhet kan være relevante, men er ikke hver for seg tilstrekkelige bevis på at et valg er etisk forsvarlig.',null],
 ['selvbestemmelsesteori',[ref(8,21,22)],'Selvbestemmelsesteori forklarer motivasjonens kvalitet gjennom autonomi, kompetanse og tilhørighet. Autonomi er opplevelsen av å stå inne for handlingen, ikke fravær av alle rammer. Ytre motivasjon kan være mer eller mindre internalisert; å oppleve et mål som viktig er ikke det samme som å like aktiviteten i seg selv.','Tre grunnbehov: autonomi, kompetanse og tilhørighet.|Ekstern regulering: belønning eller straff.|Introjeksjon: indre press, skyld eller behov for anseelse.|Identifisering: målet oppleves personlig viktig.|Indre motivasjon: interesse og glede i aktiviteten.'],
 ['forventningsteori',[ref(15,11,13),ref(8,20)],'Motivasjonen analyseres gjennom forventning om at innsats gir prestasjon, instrumentalitet mellom prestasjon og utfall, og valens som verdien av utfallet. E × I × V er en pedagogisk modell for samspillet, ikke en presis måling av menneskers motivasjon. Evner, rolleforståelse og ressurser påvirker også faktisk ytelse. Den eldre figuren i sammendraget er forenklet.','Forventning: tror jeg at innsats kan gi ønsket prestasjon?|Instrumentalitet: tror jeg at prestasjonen utløser utfallet?|Valens: er utfallet attraktivt eller uønsket for meg?|Et svakt ledd kan svekke motivasjonen selv om de andre er sterke.'],
 ['organisatorisk-tilknytning',[ref(14,11,12)],'Meyer og Allens tredeling skiller følelsesmessig, normativ og kalkulerende tilknytning. Man kan bli fordi man ønsker det, føler at man bør, eller opplever at det er kostbart å slutte. Flere bånd kan virke samtidig. Sterk tilknytning er ikke automatisk det samme som høy jobbtilfredshet eller engasjement.','Affektiv tilknytning: ønsker å tilhøre organisasjonen.|Normativ tilknytning: opplever en forpliktelse til å bli.|Kalkulerende tilknytning: vurderer tap, alternativer og kostnader ved å slutte.|Ønske om å slutte og faktisk avgang må skilles.'],
 ['ressursbasert-strategi',[ref(6,12)],'Et innenfra-og-ut-perspektiv undersøker hvilke ressurser virksomheten kan bygge en særpreget strategi på. Ressursene kan være fysiske, organisatoriske eller menneskelige. Forelesningen fremhever verdi, knapphet og vanskelighet med å kopiere. En ressurs er ikke strategisk bare fordi den er dyr; den må bidra til verdiskaping og kunne utnyttes. Perspektivet kan kombineres med analyse av markedet.',null],
 ['mintzberg-hoveddeler',[ref(13,24)],'Mintzbergs fem deler beskriver funksjoner i organisasjonen. Den operative kjernen leverer varer eller tjenester; mellomlinjen kobler den til toppledelsen; toppledelsen ivaretar overordnet retning. Teknostrukturen utvikler blant annet standarder og styringssystemer, mens støttestaben leverer indirekte støttetjenester. Virkelige stillinger kan kombinere flere funksjoner.','Operativ kjerne.|Mellomlinje.|Strategisk toppledelse.|Teknostruktur.|Støttestab.'],
 ['lederstiler',[ref(3,17,21)],'Oppgaveorientering handler om struktur, forventninger og oppfølging. Relasjonsorientering handler om støtte, tillit og involvering. De kan være høye samtidig. Autoritær eller demokratisk beslutningsform er en annen dimensjon: tydelige oppgavekrav er ikke automatisk autoritære, og hyggelig behandling er ikke nødvendigvis medbestemmelse.',null],
 ['hersey-blanchard',[ref(3,23,31)],'Situasjonsbestemt ledelse tilpasser oppgave- og relasjonsatferd til medarbeiderens forutsetninger for en bestemt oppgave. Forelesningen viser både en eldre beredskapsmodell og en senere utviklingsmodell. Punktene nedenfor følger den eldre modellen på PDF-side 24. Den senere varianten beskriver en entusiastisk nybegynner som lav i kompetanse, men høy i engasjement, med behov for tydelig instruksjon. Variantene må ikke blandes i én tabell. Vurder den konkrete oppgaven, ikke personens verdi eller en fast modenhetstype.',null],
 ['selznick-verdibasert-ledelse',[ref(3,48,52)],'Institusjonell ledelse gir virksomheten formål og særpreg utover teknisk oppgaveløsning. Selznicks funksjoner omfatter å definere formål og rolle, bygge formålet inn i organisasjonen, beskytte institusjonell integritet og håndtere interne konflikter. Verdier må få konsekvenser for organisering og prioritering, ikke bare uttrykkes i slagord.','Definere virksomhetens formål og rolle.|Bygge formålet inn i struktur, praksis og kompetanse.|Beskytte institusjonens integritet.|Håndtere interne konflikter mellom grupper og hensyn.'],
 ['kompetanseledelse',[ref(12,18,24)],'Kompetanseledelse kobler virksomhetens mål til hva medarbeidere kan, hva oppgavene krever, og hvordan kompetansen faktisk brukes. Et kompetansegap kan kreve læring eller rekruttering. Et mobiliseringsgap oppstår når eksisterende kompetanse ikke blir brukt, for eksempel på grunn av organisering, liten innflytelse eller feil oppgavefordeling. Kurs alene løser derfor ikke alle problemer.','Kartlegg kompetansekrav og eksisterende kompetanse.|Skill utviklingsbehov fra manglende bruk av kompetansen.|Tilrettelegg oppgaver, autonomi og samarbeid.|Følg opp om kompetansen blir omsatt i arbeid.'],
 ['transformasjonsledelse',[ref(3,59,63)],'Transformasjonsledelse søker å utvikle mening, engasjement og nye perspektiver utover en ren bytterelasjon. Fire komponenter er idealisert innflytelse, inspirerende motivasjon, intellektuell stimulering og individuelle hensyn. En sterk visjon er ikke automatisk etisk god; mål og maktbruk må vurderes særskilt.','Idealisert innflytelse: være en troverdig rollemodell.|Inspirerende motivasjon: skape retning og mening.|Intellektuell stimulering: utfordre antakelser og prøve nye løsninger.|Individuelle hensyn: støtte ulike medarbeideres utvikling.'],
 ['transaksjonsledelse',[ref(3,59,63)],'Transaksjonsledelse klargjør forventninger og kobler prestasjoner til belønning eller korrigering. Betinget belønning gjelder avtalte gjenytelser. Aktiv avviksledelse følger med og griper inn tidlig; passiv avviksledelse reagerer når problemer allerede har oppstått. Laissez-faire innebærer manglende ledelsesinngrep og bør ikke fremstilles som en positiv transaksjonsteknikk.','Betinget belønning.|Aktiv avviksledelse.|Passiv avviksledelse.|Skill passiv reaksjon fra helt fraværende ledelse.'],
 ['lewin',[ref(2,19),ref(2,26)],'Lewins tredeling beskriver å løsne etablerte mønstre, utvikle nye arbeidsmåter og stabilisere dem. Opptining innebærer forståelse, trygghet og motivasjon for å endre. Endringsfasen krever utprøving og støtte. Stabilisering betyr å gjøre den nye praksisen gjennomførbar og vedvarende; det betyr ikke at organisasjonen aldri skal lære eller endre seg igjen.','Opptining: undersøke og løsne etablerte mønstre.|Endring: lære og prøve nye arbeidsmåter.|Stabilisering: støtte og forankre ny praksis.'],
 ['uplanlagt-endring',[ref(2,10)],'Endring kan forstås gjennom flere perspektiver enn bevisst planlegging: livssyklus, evolusjon gjennom tilpasning og seleksjon, dialektiske interesse- og maktkamper, og tilfeldige hendelser eller sammenfall. Dette er ulike forklaringsmåter, ikke universelle lover om hvordan alle organisasjoner utvikler seg.','Livssyklus: skiftende utfordringer gjennom utviklingsfaser.|Evolusjon: variasjon, seleksjon og videreføring.|Dialektikk: motsetninger og maktkamp driver frem nye ordninger.|Tilfeldighet: hendelser og sammenfall endrer utviklingsbanen.'],
 ['maalsettingsteori',[ref(15,16,19)],'Mål kan rette oppmerksomhet, innsats og utholdenhet når de er forståelige, krevende og akseptert, og når medarbeideren får tilbakemelding og har nødvendige forutsetninger. Ved komplekse, ukjente oppgaver kan læringsmål være mer hensiktsmessige enn ensidige prestasjonsmål. Mål bør vurderes opp mot kvalitet og andre hensyn for å unngå målforskyvning.',null],
 ['maslow',[ref(15,6,7)],'Maslow grupperer behov i fysiologi, trygghet, tilhørighet, anerkjennelse og selvrealisering. Modellen kan åpne en bredere samtale om motivasjon, men skal ikke brukes som en rigid trapp der et behov må være fullstendig oppfylt før et annet finnes. Flere behov kan virke samtidig, og rekkefølge og betydning varierer.',null],
 ['konflikt-beslutningskvalitet',[ref(14,23,27)],'Saklig meningsbrytning kan avdekke alternativer og feil, mens relasjonskonflikt og eskalering kan svekke samarbeid. En skisse med et gunstig middels konfliktnivå er ingen universell doseanbefaling. Undersøk konfliktens innhold, intensitet, maktforhold og håndtering. Konflikt kan utvikle seg gjennom tolkning, følelser, intensjoner, handlinger og motreaksjoner.',null],
 ['institusjonelle-omgivelser',[ref(11,16,18)],'Regulative, normative og kognitive omgivelser former hva som oppfattes som legitim organisering. Organisasjoner kan bli likere gjennom lovkrav og avhengighet, profesjonelle normer og etterligning under usikkerhet. Slik isomorfisme betyr ikke at de valgte løsningene alltid er teknisk best eller faktisk praktiseres slik de beskrives.',null]
];
