const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>typeof v==='string'?v:JSON.stringify(v,null,2);
const names={title:'Full tittel',short_label:'Navn på noden','content.short_definition':'Kort definisjon','content.explanation':'Forklaring','content.key_points':'Hovedpunkter'};
const labels=p=>names[p]||p;
async function api(path,data){const response=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Handlingen mislyktes.');return result;}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function external(url){if(window.desktop)return window.desktop.openExternal(url);window.open(url,'_blank','noopener,noreferrer');}

export function setupSync({canLeave,reload,toast}){
  const dialog=document.createElement('dialog');dialog.id='sync-dialog';document.body.append(dialog);
  let status,plan,update,loading=false;
  const $=s=>dialog.querySelector(s);
  const show=(title,body)=>{dialog.innerHTML=`<div class="sync-heading"><h2>${esc(title)}</h2><button class="close-button" id="sync-close" aria-label="Lukk">×</button></div><div class="sync-body">${body}</div>`;$('#sync-close').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();};
  function error(message){let el=$('#sync-error');if(!el){el=document.createElement('p');el.id='sync-error';el.className='error-text';el.setAttribute('role','alert');$('.sync-body').prepend(el);}el.textContent=message;}
  async function busy(button,fn){if(loading)return;loading=true;button.disabled=true;try{await fn();}catch(e){error(e.message);}finally{loading=false;if(button.isConnected)button.disabled=false;}}
  function nativeUI(){
    const el=$('#native-update');if(!el)return;
    if(!window.desktop){el.innerHTML='<p>Appoppdateringer installeres i skrivebordsappen. Denne siden kjører som en lokal nettside.</p>';return;}
    const phase=update?.phase||'idle';const messages={idle:'Se etter en ny apputgave.',checking:'Ser etter appoppdateringer…',current:'Du har den nyeste tilgjengelige apputgaven.',available:`App ${update?.availableVersion} er tilgjengelig.`,downloading:`Laster ned appoppdatering · ${update?.percent||0} %`,ready:'Appoppdateringen er klar. Lagre arbeidet ditt før du starter på nytt.',development:update?.message,error:update?.message};
    el.innerHTML=`<p>${esc(messages[phase]||'')}</p><button class="small-button" id="native-check" ${['checking','downloading'].includes(phase)?'disabled':''}>Se etter appoppdatering</button>${phase==='available'?'<button class="primary-button" id="native-download">Last ned oppdatering</button>':''}${phase==='ready'?'<button class="primary-button" id="native-install">Start på nytt og installer</button>':''}`;
    $('#native-check').onclick=()=>busy($('#native-check'),async()=>{update=await window.desktop.checkUpdates();nativeUI();});
    if($('#native-download'))$('#native-download').onclick=()=>busy($('#native-download'),async()=>{update=await window.desktop.downloadUpdate();nativeUI();});
    if($('#native-install'))$('#native-install').onclick=()=>busy($('#native-install'),async()=>{if(canLeave())await window.desktop.installUpdate();});
  }
  async function openManager(){if(!canLeave())return;show('Oppdateringer og egne data','<p>Henter oversikt…</p>');try{
    status=await api('/api/status');update=await window.desktop?.updateStatus();
    show('Oppdateringer og egne data',`<div class="sync-version">App ${esc(status.app_version)} <span>·</span> Faginnhold ${status.content_version}</div><section class="sync-section"><h3>Oppdater fagkartet</h3><p>Hent godkjente rettelser og nye temaer. Du får se endringene før de brukes. Egne notater beholdes.</p><button class="primary-button" id="content-check">Se etter nytt faginnhold</button><div id="content-result"></div></section><section class="sync-section"><h3>Oppdater appen</h3><div id="native-update"></div></section><section class="sync-section"><h3>Sikkerhetskopi av egne endringer</h3><p>Ta med egne notater og redigeringer til en annen maskin. Filen inneholder private notater.</p><div class="sync-actions"><button class="small-button" id="backup-export">Lagre sikkerhetskopi</button><button class="small-button" id="backup-import">Åpne sikkerhetskopi</button><input id="backup-file" type="file" accept=".json,application/json" hidden></div></section>${status.archived.length?`<section class="sync-section"><h3>Notater fra utgåtte temaer</h3><p>Disse temaene finnes ikke lenger i det delte kartet. Dine tekster er beholdt og følger med sikkerhetskopier.</p>${status.archived.map(t=>`<details><summary>${esc(t.title)}</summary><p>${esc(t.notes)}</p><pre>${esc(JSON.stringify(t.fields,null,2))}</pre></details>`).join('')}</section>`:''}<p class="sync-footnote">Forslag deles fra «Foreslå endring» i et temanotat. Ingenting publiseres uten at du selv sender det på GitHub.</p>`);
    nativeUI();$('#backup-export').onclick=()=>busy($('#backup-export'),async()=>{download('Sammenheng-sikkerhetskopi.json',await api('/api/backup/export'));toast('Sikkerhetskopien er klar for lagring.');});
    $('#backup-import').onclick=()=>$('#backup-file').click();$('#backup-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20e6)throw new Error('Filen er for stor.');plan=await api('/api/backup/preview',JSON.parse(await file.text()));showPlan();}catch(e){error(e.message);}};
    $('#content-check').onclick=()=>busy($('#content-check'),async()=>{const result=await api('/api/content/check',{});const slot=$('#content-result');if(!result.available){slot.innerHTML='<p>Du har det nyeste tilgjengelige faginnholdet.</p>';return;}const u=result.update;slot.innerHTML=`<div class="update-card"><strong>Faginnhold ${u.version}</strong><p>${esc(u.notes)}</p>${u.compatible?'<button class="primary-button" id="content-preview">Last ned og forhåndsvis</button>':`<p>Oppdater appen til minst ${esc(u.min_app_version)} først.</p>`}</div>`;if($('#content-preview'))$('#content-preview').onclick=()=>busy($('#content-preview'),async()=>{plan=await api('/api/content/preview',{});showPlan();});});
  }catch(e){error(e.message);}}
  function showPlan(){
    const importing=plan.type==='backup';
    show(importing?'Gjenopprett egne endringer':`Faginnhold ${plan.version}`,`<p>${importing?`${plan.count} temanotater i sikkerhetskopien.`:esc(plan.notes)}</p>${!importing?`<p>${plan.added} nye temaer · ${plan.removed_count} utgåtte temaer. Egne notater fra utgåtte temaer arkiveres.</p>`:''}${plan.conflicts.length?`<p class="review-note">${plan.conflicts.length} felt har ulike endringer. Velg hva du vil beholde i hvert felt.</p>`:'<p>Ingen konflikter. Egne endringer og notater beholdes.</p>'}<form id="conflict-form">${plan.conflicts.map((c,i)=>`<fieldset class="conflict"><legend>${esc(c.title)} · ${esc(labels(c.path))}</legend><label><input type="radio" name="choice-${i}" value="local" required> ${importing?'Fra sikkerhetskopien':'Min tekst'}<pre>${esc(text(c.local))}</pre></label><label><input type="radio" name="choice-${i}" value="shared" required> ${importing?'Teksten på denne maskinen':'Ny felles tekst'}<pre>${esc(text(c.shared))}</pre></label></fieldset>`).join('')}<div class="sync-actions"><button class="primary-button" type="submit">${importing?'Gjenopprett valgte tekster':'Bruk innholdsoppdateringen'}</button><button class="small-button" type="button" id="plan-cancel">Avbryt</button></div></form>`);
    $('#plan-cancel').onclick=openManager;$('#conflict-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form),choices=Object.fromEntries(plan.conflicts.map((c,i)=>[c.key,fd.get('choice-'+i)]));busy(form.querySelector('[type=submit]'),async()=>{await api(importing?'/api/backup/apply':'/api/content/apply',{id:plan.id,choices});await reload();dialog.close();toast(importing?'Sikkerhetskopien er gjenopprettet.':'Fagkartet er oppdatert. Egne notater er beholdt.');});};
  }
  async function propose(id){if(!canLeave())return;show('Foreslå en felles rettelse','<p>Henter endringene dine…</p>');try{
    const p=await api('/api/proposals/'+encodeURIComponent(id));
    if(!p.changes.length){show('Foreslå en felles rettelse','<p>Ingen endringer i navn, definisjon, forklaring eller hovedpunkter å foreslå. Rediger og lagre temaet først. Egne notater deles aldri som forslag.</p>');return;}
    show('Foreslå en felles rettelse',`<p>Velg feltene du vil foreslå for <strong>${esc(p.topic_title)}</strong>. Forslaget blir synlig i GitHub-repositoryet når du sender det der. Du trenger en GitHub-konto.</p><p class="review-note">Egne notater blir ikke inkludert.</p><form id="proposal-form">${p.changes.map((c,i)=>`<label class="proposal-field"><span><input type="checkbox" name="field" value="${esc(c.path)}" checked> ${esc(labels(c.path))}</span><small>Felles tekst</small><pre>${esc(text(c.before))}</pre><small>Din foreslåtte tekst</small><pre>${esc(text(c.after))}</pre></label>`).join('')}<label class="proposal-reason">Begrunnelse (valgfritt)<textarea name="explanation" maxlength="4000" rows="3" placeholder="Hvorfor gjør dette forklaringen bedre?"></textarea></label><button type="submit" class="primary-button">Klargjør forslag</button></form>`);
    $('#proposal-form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);busy(e.currentTarget.querySelector('button'),async()=>{const prepared=await api('/api/proposals/'+encodeURIComponent(id),{paths:fd.getAll('field'),explanation:fd.get('explanation')});show('Forslaget er klart',`<p>${prepared.proposal.changes.length} felt er valgt. Ingen private notater er med.</p><p>${prepared.needs_paste?'Forslaget er langt. Kopier teksten nedenfor, åpne GitHub og lim den inn i beskrivelsen.':'GitHub åpnes med forslaget ferdig utfylt. Kontroller det og trykk på knappen for å sende inn saken.'}</p><details><summary>Vis hele forslaget</summary><pre id="proposal-text">${esc(prepared.text)}</pre></details><div class="sync-actions"><button class="primary-button" id="proposal-open">${prepared.needs_paste?'Kopier og åpne GitHub':'Åpne forslag på GitHub'}</button><button class="small-button" id="proposal-copy">Kopier tekst</button><button class="small-button" id="proposal-download">Lagre forslagsfil</button></div><p id="proposal-status" role="status"></p>`);
      $('#proposal-open').onclick=()=>busy($('#proposal-open'),async()=>{if(prepared.needs_paste)await navigator.clipboard.writeText(prepared.text);await external(prepared.url);$('#proposal-status').textContent='Fullfør innsendingen på GitHub. Appen har ikke sendt forslaget.';});
      $('#proposal-copy').onclick=()=>busy($('#proposal-copy'),async()=>{await navigator.clipboard.writeText(prepared.text);toast('Forslagsteksten er kopiert.');});
      $('#proposal-download').onclick=()=>download('forslag-'+id+'.json',prepared.proposal);
    });};
  }catch(e){error(e.message);}}
  document.querySelector('#updates-button').onclick=openManager;
  window.desktop?.onUpdate(value=>{update=value;nativeUI();if(['available','ready'].includes(value.phase))document.querySelector('#updates-button').classList.add('has-update');});
  return {propose,openManager};
}
